CREATE ROLE DATA_ENGINEER_ROLE;
CREATE ROLE DATA_ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE ENTERPRISE_DB TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON SCHEMA ENTERPRISE_DB.STAGING TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ENTERPRISE_DB.STAGING TO ROLE DATA_ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA ENTERPRISE_DB.ACCESS TO ROLE DATA_ANALYST_ROLE;
